### PR TITLE
Add support for ECDSA Key Type `P-384`.

### PR DESCRIPTION
**Pull request by JSAssassin**
~Related PR - https://github.com/digitalbazaar/bedrock-did-io/pull/18 (Adds `P-384` to the default key types in the DID method `key` config.)~ merged.

issued VC => 

```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    {
      "ex": "https://example.org/examples#",
      "schema": "http://schema.org/",
      "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
      "BachelorDegree": "ex:BachelorDegree",
      "UniversityDegreeCredential": "ex:UniversityDegreeCredential",
      "degree": "ex:degree",
      "name": {
        "@id": "schema:name",
        "@type": "rdf:HTML"
      }
    },
    "https://w3id.org/security/data-integrity/v1"
  ],
  "id": "http://example.gov/credentials/3732",
  "type": [
    "VerifiableCredential",
    "UniversityDegreeCredential"
  ],
  "issuer": "did:key:z82LkvS9rECtUuWj4grN2BL5rMuaBeBYRw8uJx1WS3qzZ8ToYsKRuj6xC4hJd57prKuqnKA",
  "issuanceDate": "2020-03-11T23:09:06.803Z",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "degree": {
      "type": "BachelorDegree",
      "name": "Bachelor of Science and Arts"
    }
  },
  "proof": {
    "type": "DataIntegrityProof",
    "created": "2023-08-07T19:43:43Z",
    "verificationMethod": "did:key:z82LkvS9rECtUuWj4grN2BL5rMuaBeBYRw8uJx1WS3qzZ8ToYsKRuj6xC4hJd57prKuqnKA#z82LkvS9rECtUuWj4grN2BL5rMuaBeBYRw8uJx1WS3qzZ8ToYsKRuj6xC4hJd57prKuqnKA",
    "cryptosuite": "ecdsa-2019",
    "proofPurpose": "assertionMethod",
    "proofValue": "zazcNJNFcU4kXM4sdBazy8z5Qmg6pjACuHnudfGj6nRgLoGNVy99f1vv6A4XEYAPFaBPUHuX4Tgdxpv3jED5aEWAreENcinDsoE2161kmuueMrToRFnJEb5Wp5F6mXdN3xXj"
  }
}
```

### CODE REVIEW

**Comment by dlongley** [comment]
@JSAssassin,

Are we able to remove all of the `keyType` additions here and instead fetch the given key description and determine the key type from its public key's multikey header?

**Comment by JSAssassin** [comment]
> Are we able to remove all of the `keyType` additions here and instead fetch the given key description and determine the key type from its public key's multikey header?

@dlongley I added `keyType` since `ecdsa-2019` now have two key types and I needed a way to determine the appropriate key type to use to generate the `referenceId` that is used to get the zcap from the config in `getSuiteParams()`.  https://github.com/digitalbazaar/bedrock-vc-issuer/blob/fada2f5c36055cd3ee88a59af37718be8694e856/lib/suites.js#L27-L30 https://github.com/digitalbazaar/bedrock-vc-issuer/blob/fada2f5c36055cd3ee88a59af37718be8694e856/lib/suites.js#L41-L56

I can try doing what you've suggested but I am not sure where exactly that should happen and if that would address the issue I've described.

**Comment by JSAssassin** [comment]
@dlongley I've removed the requirement for providing `keyType` parameter from both the issue and status list options. Now instead, for the `ecdsa-2019` suite, we check the config and get the key type that is specified in the name of the assertion method zcap. 

https://github.com/digitalbazaar/bedrock-vc-issuer/blob/b624cdc9078d8af347345bacfc7082242fbb5bbd/lib/suites.js#L41-L60

**Comment by dlongley** [comment]
The problem here has to do with making sure systems don't have to know "special information" like to parse zcap names or pass key types explicitly; these things should be appropriately parameterized and encapsulated.

Hmm... I'm wondering if what we need to do is generate the zcap name using the algorithm instead of the key type. There's some conflation between algorithm and key type that we've been both leveraging to understand key type differences and that has caused trouble. We need to figure out what to do about it going forward. We should see if we can create the zcap name just based on the signing algorithm (`ecdsa`) -- and what other changes might be required to accomplish that simply. At the very least, we could have an internal mapping from key type to algorithm where the zcap is generated to accomplish it -- but ideally we'd pull it from the key metadata.

**Comment by dlongley** [comment]
@mattcollier,

It's blocked on figuring out what to do in lower level KMS-related libs that express key information such as key types, curves, and algorithms.

**Comment by dlongley** [comment]
@JSAssassin,

Suppose we made it such that the zcap used a `referenceId` that didn't include the key type / algorithm / curvename in it and just said `assertionMethod`. What kind of problems, if any, would this cause?

**Comment by dlongley** [comment]
@JSAssassin,

> Are there any scenarios where we might need to support multiple assertion methods?

I don't think so ... I think we should just draw the line there and say that another configuration (and thus another instance) needs to be used to use another assertion method.

**Pull request closed without merging**
